### PR TITLE
Add links to README.md

### PR DESCRIPTION
**Pull request by adomani**
I added `md`-formatted links to the tactics that appear in Mathlib4.  I have not checked all the links, but a sample of them worked!

Let me know if you want me to include the "very primitive auto-linking" tool.

### CODE REVIEW

**Comment by madvorak** [comment]
Thank you!

Should `by_contradiction` be translated to `by_contra` or to `by_contra'` instead?
There is a little inconsistency now.

**Comment by adomani** [comment]
I think that some of the `tactic'`  will disappear after the port, replaced by the non-primed name.  It seems that there is a choice between
* the dictionary is correct now, but it will possibly rot later on,
* the dictionary is not entirely accurate now, but possibly it will be correct later on.

I'll leave this up to you!

**Comment by madvorak** [comment]
It looks great! Thank you! Now it is easy to keep editing it manually, in addition to having the option to generate links in bulk by your script!

**Comment by madvorak** [comment]
> I think that some of the `tactic'` will disappear after the port, replaced by the non-primed name. It seems that there is a choice between
> 
> * the dictionary is correct now, but it will possibly rot later on,
> * the dictionary is not entirely accurate now, but possibly it will be correct later on.
> 
> I'll leave this up to you!

I better keep the primed tactics for now; if they disappear, I will remove them.
Is there a reasons for `by_contra'` to be a better replacement for `by_contradition` than `by_contra` is?

**Comment by madvorak** [comment]
Can individual tactics in
https://leanprover-community.github.io/mathlib4_docs/Std/Tactic/Basic.html
be referenced?

**Comment by adomani** [comment]
Yes, *if* the name is correct, then it is simply a matter of appending `#<declarationName>` to the URL.  However, in the case of the `tactic'`, if you use the wrong name, the link will point to the file only, rather than the actual tactic.  I can automate the appending of the guessed link: whether it actually links to the tactic or the file will depend on the available data.

**Comment by madvorak** [comment]
> 

Yeah, I want to have it! You can append `#<declarationName>` for all of `std4` tactics and I will delete those that go to 404.

**Comment by madvorak** [comment]
Actually the wrong ones go to the top of the page. That is even less dangerous.

**Comment by madvorak** [comment]
Feature request:
Can we do a similar thing for https://leanprover-community.github.io/mathlib4_docs/Init/Tactics.html please?

**Comment by adomani** [comment]
Did you mean to link the community webpage or your other "mathlib tactics" webpage?

In any case, I'll look into it once I'm back home.

Also, as you've seen, if the URL is correct, you won't get an error, the browser will silently not open at the correct anchor.

**Comment by madvorak** [comment]
I think https://leanprover-community.github.io/mathlib4_docs/Init/Tactics.html documents the core tactics.

**Comment by adomani** [comment]
Ah, I see: add links to the core tactics as well!  Yes, that should be straightforward.

**Comment by madvorak** [comment]
Yeah, and with `#<declarationName>` if possible. Again, I don't mind if your script leaves something that doesn't have a target. I don't mind "postprocessing" all the items.

**Comment by madvorak** [comment]
A lot of stuff is written twice, like `contradictioncontradiction` and similar.

**Pull request merged**
